### ISSUE TITLE
Deploy to Cluster Crashes - Unable to Start EGO-UI Service

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/dms#69]
In DMS 0.7.1, when deploying config to cluster ("dms cluster apply"), all services start except EGO-UI

The DMS script crashes ungracefully throwing the following Java Exception:

`java.util.concurrent.CompletionException: net.jodah.failsafe.FailsafeException: java.net.UnknownHostException: ego-api: System error
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)`

Environment:

- macOS Catalina 10.15.7
- 3.1 GHz Quad-Core Intel Core i7
- 16 GB RAM 2133 MHz LPDDR3

**Comment by blabadi** [comment]
ready for retest, note that the docker script was updated, so you need to redownload it from git 

`
curl https://raw.githubusercontent.com/overture-stack/dms/0.7.2/src/main/bin/dms-docker > dms

**Comment by b-f-chan** [comment]
Re-tested in DMS 0.7.0, bug no longer occurs, able to deploy services successfully.  Closing.
